package ua.bot.html_parser.utils;

import java.util.ArrayList;
import java.util.List;

public enum HtmlTags {
    A("a"),
    ABBR("abbr"),
    ACRONYM("acronym"),
    ADDRESS("address"),
    APPLET("applet"),
    AREA("area"),
    ARTICLE("article"),
    ASIDE("aside"),
    AUDIO("audio"),
    B("b"),
    BASE("base"),
    BASEFONT("basefont"),
    BDO("bdo"),
    BIG("big"),
    BLOCKQUOTE("blockquote"),
    BODY("body"),
    BR("br"),
    BUTTON("button"),
    CANVAS("canvas"),
    CAPTION("caption"),
    CENTER("center"),
    CITE("cite"),
    CODE("code"),
    COL("col"),
    COLGROUP("colgroup"),
    DATALIST("datalist"),
    DD("dd"),
    DEL("del"),
    DFN("dfn"),
    DIV("div"),
    DL("dl"),
    DT("dt"),
    EM("em"),
    EMBED("embed"),
    FIELDSET("fieldset"),
    FIGCAPTION("figcaption"),
    FIGURE("figure"),
    FONT("font"),
    FOOTER("footer"),
    FORM("form"),
    FRAME("frame"),
    FRAMESET("frameset"),
    HEAD("head"),
    HEADER("header"),
    H6("h6"),
    HR("hr"),
    HTML("html"),
    I("i"),
    IFRAME("iframe"),
    IMG("img"),
    INPUT("input"),
    INS("ins"),
    KBD("kbd"),
    LABEL("label"),
    LEGEND("legend"),
    LI("li"),
    LINK("link"),
    MAIN("main"),
    MAP("map"),
    MARK("mark"),
    META("meta"),
    METER("meter"),
    NAV("nav"),
    NOSCRIPT("noscript"),
    OBJECT("object"),
    OL("ol"),
    OPTGROUP("optgroup"),
    OPTION("option"),
    P("p"),
    PARAM("param"),
    PRE("pre"),
    PROGRESS("progress"),
    Q("q"),
    S("s"),
    SAMP("samp"),
    SCRIPT("script"),
    SECTION("section"),
    SELECT("select"),
    SMALL("small"),
    SOURCE("source"),
    SPAN("span"),
    STRIKE("strike"),
    STRONG("strong"),
    STYLE("style"),
    SUB("sub"),
    SUP("sup"),
    TABLE("table"),
    TBODY("tbody"),
    TD("td"),
    TEXTAREA("textarea"),
    TFOOT("tfoot"),
    TH("th"),
    THEAD("thead"),
    TIME("time"),
    TITLE("title"),
    TR("tr"),
    U("u"),
    UL("ul"),
    VAR("var"),
    VIDEO("video"),
    WBR("wbr");

    public final String label;

    private HtmlTags(String label) {
        this.label = label;
    }

    public static List<String> getListTagLabel(){
        List<String> list = new ArrayList<>();
        for ( HtmlTags tag : HtmlTags.values()) {
            list.add(tag.label);
        }
        return list;
    }
}
